EH-1412: Työpaikkajakson keston laskentatavan muutos
Opetushallitus/heratepalvelu pull request #240
Opened 2023-06-08 07:16 UTC by severij

2023-06-30 00:13 UTC, pkalliok requested changes
Täs on paljon sellaista pikku valitusta, jota ei oo pakko ottaa huomioon.  Mut se mikä oikeasti vaikeuttaa tän koodin lukemista, on se, että ei oo mitään (funktion nimissä, dokumentaatiossa, esi- tai jälkiehdoissa, skeemoissa) josta pystyis päättelemään, minkämuotoisia tietoja nää funktiot ottaa sisään ja palauttaa.

Ehkä paras lähestymistapa olis nimetä funktiot palautusarvon mukaan ja tehdä niille skeemat?  Lisäks olis hyvä dokumentoida sellaiset oletukset kuin että tietty funktio ottaa vastaan vain yhden oppijan työpaikkajaksoja.

Jos tällä uudella laskennalla on kiire, nää parannukset voi kyllä tehdä erillisessäkin PR:ssa.

Varsinaisia logiikkavirheitä en huomannut, mut tää laskentasysteemi ei oo mulle kovin tuttu.  Pitäis varmaan katsoa, kuinka paljon tällä on vanhastaan erilaisia testejä.

2023-06-30 00:13 UTC, pkalliok commented on src/oph/heratepalvelu/util/date.clj
> +             (if (pos? (compare % d)) % d)) dates))
Tän ei mun mielestä kannata olla varargs ku sitä kuitenkin kutsutaan applyn avulla.
```suggestion
(defn max-date [dates]
  (last (sort dates)))
```

2023-06-30 00:13 UTC, pkalliok commented on src/oph/heratepalvelu/util/date.clj
> +(defn range
tää on musta magee :)

2023-06-30 00:13 UTC, pkalliok commented on src/oph/heratepalvelu/util/date.clj
> +           (= (.getDayOfWeek date) DayOfWeek/SUNDAY))))
Tätä ei taideta enää käyttää missään, joten, vaikka hieno onkin, sen voisi poistaa testeineen.

2023-06-30 00:13 UTC, pkalliok commented on src/oph/heratepalvelu/util/string.clj
> +             (if (pos? (compare % s)) % s)) strs))
```suggestion
(defn max-str [strs]
  (last (sort strs)))
```

2023-06-30 01:24 UTC, pkalliok commented
Katsoin vielä testejä, kun kerran pohdin niitä tuossa.  Vaikuttaa siltä, että jyvitys on aika hyvin testattu, mutta keskeytymisajanjaksojen vaikutuksen kattavuus on aika hankala lukea :)  Mut äkkiseltään lukemalla vaikutti ainakin siltä, että niitä opiskeluoikeuksia ei ole testeissä, joiden keskeytymisajanjaksot vaikuttais jollain tavalla muiden jaksojen jyvitykseen.

2023-06-30 14:46 UTC, severij commented on src/oph/heratepalvelu/tep/niputusHandler.clj
> +                                       concurrent-jaksot)]
Laitoin muistiin, että tehdään näistä tiketti :+1:

2023-06-30 16:08 UTC, severij commented on src/oph/heratepalvelu/tep/niputusHandler.clj
> +         [])))
Tiketöity: https://jira.eduuni.fi/browse/EH-1524

2023-06-30 16:08 UTC, severij commented on src/oph/heratepalvelu/tep/niputusHandler.clj
> +    jaksot))
Tiketöity: https://jira.eduuni.fi/browse/EH-1524

2023-06-30 16:58 UTC, severij commented on src/oph/heratepalvelu/tep/niputusHandler.clj
> +         [])))
Itseasiassa korjaskinkin tämän :sweat_smile:  Olin varmaan merge conflicteja ratkoessa poistanu tuon sun tekemän `add-loppu-to-jaksot` funktion tai sit se oli pudonnu kelkasta rebasen yhteydessä :thinking:  Oli miten oli, laitoin tuon funktion takasin niputusHandlerin koodiin.

2023-07-12 14:35 UTC, severij commented
Ennen testaamista QA:lla tein tosiaan sanity checkin, jossa tarkistettu, että kestonlaskennan muutokset refaktorointeineen tuottaa samat tulokset kuin vanha kestonlaskentafunktio, johon on tehty EH-1412 ja EH-1414 kuvatut muutokset, sekä se, että kestoksi asetetaan nolla kun opiskeluoikeutta ei löydy. Tämän tein tosiaan vain tarkistamaan, ettei toiminnallisuus ole muuttunut mitenkään odottamattomalla tavalla refaktoroinnin jäljiltä.

Ennen QA:lla testaamista tein myös excelin testitapauksista, jotka löytyy tiketin https://jira.eduuni.fi/browse/EH-1412 liiteistä. Loin QA:lla opiskelijoille BBB ja CCC hoksit, joihin sisältyy excelissä kuvatut jaksot. Koska jaksojen päättymispäivät olivat testaushetkellä menneisyydessä, piti eHOKSin kannasta täpätä `tep_kasitelty` lippu jaksoille takaisin arvoon `false`, jolloin ne tulivat poimituksi Herätepalveluun `timedOperationsHandler`-lambdan toimesta. Ennen niputusta jouduin muuttamaan eHOKSista sekä `jaksotunnusTable`-taulusta parin testijakson osa-aikaisuuden ei-validiksi ja tyhjäksi, muutoin nämä eivät olisi päätyneet validointivirheen seurauksena lainkaan Herätepalveluun. Lisäksi yhtä jaksoa (ja hoksia) vastaavan opiskeluoikeuden poistin, jotta tulisi testattua myös toiminnallisuus kun opiskeluoikeutta ei saada Koskesta.

Ennen `niputusHandler`-lambdan käynnistämistä asetin jaksojen `niputuspvm` kenttiin arvon `2023-07-12`, eli päivän jolloin testasin toiminnallisuutta QA:lla. Vastaavasti nipputaulusta piti asettaa jaksoja vastaavien nippujen `niputuspvm` kenttään päivämäärä `2023-07-12`. niputusHandlerin ajon jälkeen kaikille jaksoille oli onnistuneesti laskettu kesto. Jaksoilla, joiden osa-aikaisuus oli tyhjä tai ei-validi oli asetettu kestoksi nolla. Näistä näkyi tulleen myös asianmukaiset lokitukset niputusHandlerin lokeille. Vastaavasti jaksolle, jonka tapauksessa opiskeluoikeutta ei löytynyt, tuli kestoksi nolla. Tästä tuli myös lokitus.

2023-07-13 07:26 UTC, merged